---
- hosts: docker_dev
  become: true
#  tasks:
#    - debug: var=ansible_all_ipv4_addresses
#    - debug: var=ansible_default_ipv4.address
#    - debug: var={{ ansible_eth1.ipv4.address }}
#    - debug: var={{inventory_hostname}}
#    - debug: var={{ansible_hostname}}
  roles:
    - {role: dockerswarm, tags: [dockerswarm]}
