---

- name: docker info
  command: docker info
  register: swarm_active

- name: Initialize swarm mode
  command: docker swarm init --advertise-addr {{ ansible_eth1.ipv4.address }}
  when: inventory_hostname in groups['docker_dev_manager'] and swarm_active.stdout.find('ClusterID') == -1

- name: Get the worker token
  command: docker swarm join-token worker -q
  register: worker_token
  when: inventory_hostname == groups['docker_dev_manager'][0]

- name: Join Manager Node
  command: docker swarm join --token {{hostvars[groups['docker_dev_manager'][0]]["worker_token"]["stdout"]}} {{groups['docker_dev_manager'][0]}}:2377
  when: inventory_hostname not in groups['docker_dev_manager'] and swarm_active.stdout.find('ClusterID') == -1

- name: 
  command: docker service create --name portainer --publish 9000:9000 --constraint 'node.role == manager' --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock portainer/portainer -H unix:///var/run/docker.sock
  when: inventory_hostname == groups['docker_dev_manager'][0]
